#!/bin/sh

echo "File Name: $ANZ Insurance"
echo "First Parameter : $ANZ"
echo "Second Parameter : $Insurance"
echo "Quoted Values: $@"1
echo "Quoted Values: $*"2
echo "Total Number of Parameters : $#"4
